<?php

namespace OC\LeetchifakeBundle\Repository;

/**
 * cagnotteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cagnotteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllCagnotteByUser($user)
    {
        $queryBuilder = $this ->createQueryBuilder('c');
        $c = $queryBuilder
        ->innerjoin('c.user','us')
        ->innerjoin('c.image','im')
        ->innerjoin('c.types','ty')
        ->addSelect('us')
        ->addSelect('im')
        ->addSelect('ty')
        ->where('us.username = :user')
        ->setParameter('user', $user);
        
        return $c
        ->getQuery()
        ->getResult();
    }
    
    public function findAllCagnotteByType($types)
    {
        $queryBuilder = $this ->createQueryBuilder('c');
        $c = $queryBuilder
        ->innerjoin('c.user','us')
        ->innerjoin('c.image','im')
        ->innerjoin('c.type','ty')
        ->addSelect('us')
        ->addSelect('im')
        ->addSelect('ty')
        ->where('ty.nom = :type')
        ->setParameter('type', $types);
        
        return $c
        ->getQuery()
        ->getResult();
        
    }
    
    
    public function  findAllCagnotteByTypeAndNom($types,$noms)
    {
        $queryBuilder = $this->createQueryBuilder('c');
        $c = $queryBuilder 
        ->innerjoin('c.user','us')
        ->innerjoin('c.image','im')
        ->innerjoin('c.type','ty')
        ->addSelect('us')
        ->addSelect('ty')
        ->addSelect('im')
        ->where('ty.nom = :type')
        ->andWhere('c.nom LIKE :nom')
        ->setParameter('nom',$noms)
        ->setParameter('type',$types)
        ;
        
        return $c
        ->getQuery()
        ->getResult()
        ;
    }
    
}
