<?php

namespace OC\LeetchifakeBundle\Repository;

/**
 * typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeRepository extends \Doctrine\ORM\EntityRepository
{
}
