services:
#    oc_user.example:
#        class: OC\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

#    Fixtures services
            OC\UserBundle\DataFixtures\ORM\UserFixtures:
                tags: [doctrine.fixture.orm]
